# Conda
conda_source: "/optnfs/common/miniconda3/etc/profile.d/conda.sh"
trax_conda: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/envs/trax_env"

# Sample file metadata
sample_tsv: "runfile.txt"

# library layout
layout: "single"

# 3' UMIs present?
UMIs: "no"

# Umi Length
umilength: 0